<?php 
	echo $this->addCss('Library/css/fangliste/hinzufuegen.css');
	echo $this->addScript('Library/js/fangliste/hinzufuegen.js');
?>
<form action="./<?= $this->controller . DIRECTORY_SEPARATOR . $this->action ?>" method="post" >
	<input type="hidden" name="benutzer" class="form-feld" value="<?= $this->user->id ?>" />
	<input type="hidden" name="bilderliste" id="bilderliste" class="form-feld" value="" />
	
	<table id="hinzufuegen-table" class="table table-form">
		<thead>
			<tr class="row heading">
				<th class="table-form-heading border" colspan="2" >Fang hinzufügen</th>
				<th class="table-form-heading border" ></th>
			</tr>
		</thead>
		<tfoot>
			<tr class="row footer">
				<td class="table-form-footer border" ></td>
				<td class="table-form-footer border" ></td>
				<td class="table-form-footer border" ></td>
			</tr>
		</tfoot>
		<tbody>

			<tr class="row">
				<td class="table-form-data label" ><label for="datum" >Datum</label></td>
				<td class="table-form-data feld" ><input required type="datetime" name="datum" class="form-feld" ></td>
			</tr>
			
			<tr class="row">
				<td class="table-form-data label" ><label for="uhrzeit" >Uhrzeit</label></td>
				<td class="table-form-data feld" ><input required type="time" name="uhrzeit" class="form-feld" ></td>
				<!--<td class="table-form-data info" ></td>-->
			</tr>

			<tr class="row">
				<td class="table-form-data label" ><label for="fischart" >Fischart</label></td>
				<td class="table-form-data feld" >
					<select required name="fischart" class="form-feld fischart" >
						<?php foreach($this->fischarten as $key => $obj): ?>
							<option value="<?= $obj->id ?>" ><?= $obj->name ?></option>
						<?php endforeach; ?>
					</select>
				</td>
				<!--<td class="table-form-data info" ></td>-->
			</tr>
			
			<tr class="row">
				<td class="table-form-data label" ><label for="gewaesser" >Gewaesser</label></td>
				<td class="table-form-data feld" >
					<select required name="gewaesser" class="form-feld gewaesser" >
						<?php foreach($this->gewaesser as $key => $obj): ?>
							<option value="<?= $obj->id ?>" ><?= $obj->bezeichnung ?></option>
						<?php endforeach; ?>
					</select>
				</td>
				<!--<td class="table-form-data info" ></td>-->
			</tr>
			
			<tr class="row">
				<td class="table-form-data label" ><label for="koeder" >Köder</label></td>
				<td class="table-form-data feld" >
					<select required name="koeder" class="form-feld koeder" >
						<?php foreach($this->koeder as $key => $obj): ?>
							<option value="<?= $obj->id ?>" ><?= $obj->name ?></option>
						<?php endforeach; ?>
					</select>
				</td>
				<!--<td class="table-form-data info" ></td>-->
			</tr>
			
			<tr class="row">
				<td class="table-form-data label" ><label for="laenge" >Länge in cm</label></td>
				<td class="table-form-data feld" ><input required type="number" maxlength="10" name="laenge" class="form-feld" ></td>
				<!--<td class="table-form-data info" ></td>-->
			</tr>
			
			<tr class="row">
				<td class="table-form-data label" ><label for="gewicht" >Gewicht in g</label></td>
				<td class="table-form-data feld" ><input required type="number" maxlength="10" name="gewicht" class="form-feld" ></td>
				<!--<td class="table-form-data info" ></td>-->
			</tr>

			<tr class="row">
				<td class="table-form-data label" ></td>
				<td class="table-form-data feld" ><input type="submit" name="submit" class="form-feld submit" value="Anlegen" ></td>
			</tr>

			<tr class="row">
				<td class="table-form-data" colspan="3" >
			</tr>

		</tbody>
	</table>
	<div id="fileupload">
		<input type="file" name="bilder" id="bilder" class="form-feld" multiple="multiple">
	</div>
	
</form>

